name: Installing Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.os }}
        

